/*
 Each new term in the Fibonacci sequence is generated by adding
 the previous two terms. By starting with 1 and 2,
 the first 10 terms will be:
    6  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 By considering the terms in the Fibonacci sequence whose values
 do not exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[]){
  if (argc != 2){
    printf("max number is required as argument to script\n");
    return 1;
  }
  int max_number = atoi(argv[1]);
  int answer = 0;
  int fib_value = 1;
  int current_number = 1;
  int previous_number = 1;
  while (fib_value < max_number){
    printf("Current number: %i\n", current_number);
    fib_value = current_number;
    if (fib_value >= max_number){
      printf("Answer is: %i\n", answer);
      return 0;
    }
    if (fib_value % 2 == 0){
      answer += current_number;
    }
    current_number += previous_number;
    previous_number = current_number - previous_number;
  }
  return 0;
}
